// GENERATED by scripts/generate-icons.mjs from scripts/icon-manifest.json — do not edit.
import { Defs, G, LinearGradient, Path, Stop } from 'react-native-svg';

import { createAiLogo } from '../create-ai-logo';

/** The StepFun mark — full colour by default, `variant="mono"` for one colour. */
export const AiLogoStepFun = createAiLogo({
  name: "StepFun",
  mono: ({ fill }) => (
    <G fill={fill} fillRule="evenodd">
      <Path d="M12 0C5.372 0 0 5.372 0 12s5.372 12 12 12 12-5.372 12-12S18.628 0 12 0zM8.762 19.614H4.376v-4.386h4.386v4.386zm5.423 0H9.798v-4.386h4.387v4.386zm0-5.42H9.798V9.81h4.387v4.386zm0-5.418H9.798V4.39h4.387v4.386zm5.422-.004h-4.386V4.386h4.386v4.386z" />
    </G>
  ),
  color: ({ id, url }) => (
    <>
      <Path d="M22.012 0h1.032v.927H24v.968h-.956V3.78h-1.032V1.896h-1.878v-.97h1.878V0zM2.6 12.371V1.87h.969v10.502h-.97zm10.423.66h10.95v.918h-6.208v9.579h-4.742V13.03zM5.629 3.333v12.356H0v4.51h10.386V8L20.859 8l-.003-4.668-15.227.001z" fill={url(0)} fillRule="evenodd" />
      <Defs>
        <LinearGradient gradientUnits="userSpaceOnUse" id={id(0)} x1="1.646" x2="18.342" y1="1.916" y2="22.091">
          <Stop stopColor="#01A9FF" />
          <Stop offset="1" stopColor="#0160FF" />
        </LinearGradient>
      </Defs>
    </>
  ),
});
