// GENERATED by scripts/generate-icons.mjs from scripts/icon-manifest.json — do not edit.
import { ClipPath, Defs, G, LinearGradient, Mask, Path, Stop } from 'react-native-svg';

import { createAiLogo } from '../create-ai-logo';

/** The Poolside mark — full colour by default, `variant="mono"` for one colour. */
export const AiLogoPoolside = createAiLogo({
  name: "Poolside",
  mono: ({ fill, id, url }) => (
    <G fill={fill} fillRule="evenodd">
      <G clipPath={url(4)}>
        <Mask height="24" id={id(0)} maskUnits="userSpaceOnUse" width="24" x="0" y="0">
          <Path d="M24 0H0v24h24V0z" fill={url(1)} />
          <Path d="M24 0H0v24h24V0z" fill={url(2)} />
          <Path d="M24 0H0v24h24V0z" fill={url(3)} />
        </Mask>
        <G mask={url(0)}>
          <Path d="M6.742 22.786a11.93 11.93 0 01-5.232-4.963 11.98 11.98 0 01-1.463-6.886.975.975 0 011.943.173c-.178 2.005.246 4 1.226 5.769a9.968 9.968 0 003.526 3.685l4.586-9.405c-1.795-.598-3.29-.338-3.425-.312l-.058.012a.972.972 0 01-1.054-.576c-.24-.448-.96-1.544-1.834-1.97-.873-.426-2.218-.289-2.651-.195a.977.977 0 01-1.087-1.38C4.117.792 11.315-1.686 17.262 1.215c5.946 2.9 8.422 10.093 5.529 16.038l-.01.02c-2.903 5.94-10.095 8.414-16.039 5.514zm6.338-10.773l-4.586 9.405c4.629 1.73 9.896-.192 12.304-4.558-.338-.524-.932-1.275-1.62-1.61-.888-.434-2.19-.292-2.637-.198a.989.989 0 01-.616-.055.984.984 0 01-.49-.473c-.028-.058-.739-1.438-2.355-2.51zM5.81 6.56c.747.365 1.356.944 1.81 1.49 1.406-2.15 3.314-3.774 4.787-4.82a20.81 20.81 0 011.66-1.067A10.078 10.078 0 003.882 6.077c.617.042 1.297.174 1.929.482zm12.671-2.243c.09.624.152 1.294.182 1.965.083 1.801-.021 4.296-.844 6.722.686.018 1.484.14 2.214.495.652.318 1.198.8 1.628 1.28a10.082 10.082 0 00-3.18-10.462zm-5.394 5.46a9.522 9.522 0 012.984 2.287c1.075-3.493.606-7.402.215-8.85-1.381.584-4.75 2.62-6.84 5.618a9.515 9.515 0 013.64.944z" />
        </G>
      </G>
      <Defs>
        <LinearGradient gradientUnits="userSpaceOnUse" id={id(1)} x1="6.75" x2="5.625" y1="20.55" y2="20.55">
          <Stop stopColor="#fff" />
          <Stop offset="1" stopColor="#fff" stopOpacity="0" />
        </LinearGradient>
        <LinearGradient gradientUnits="userSpaceOnUse" id={id(2)} x1="6.825" x2="7.2" y1="11.85" y2="11.137">
          <Stop stopColor="#fff" stopOpacity="0" />
          <Stop offset="1" stopColor="#fff" />
        </LinearGradient>
        <LinearGradient gradientUnits="userSpaceOnUse" id={id(3)} x1=".975" x2=".975" y1="20.512" y2="10.912">
          <Stop stopColor="#fff" />
          <Stop offset=".105" stopColor="#fff" stopOpacity=".9" />
          <Stop offset=".904" stopColor="#fff" stopOpacity=".04" />
          <Stop offset="1" stopColor="#fff" stopOpacity="0" />
        </LinearGradient>
        <ClipPath id={id(4)}>
          <Path d="M0 0h24v24H0z" fill={fill} />
        </ClipPath>
      </Defs>
    </G>
  ),
  color: ({ id, url }) => (
    <>
      <G clipPath={url(4)}>
        <Mask height="24" id={id(0)} maskUnits="userSpaceOnUse" width="24" x="0" y="0">
          <Path d="M24 0H0v24h24V0z" fill={url(1)} />
          <Path d="M24 0H0v24h24V0z" fill={url(2)} />
          <Path d="M24 0H0v24h24V0z" fill={url(3)} />
        </Mask>
        <G mask={url(0)}>
          <Path d="M6.742 22.786a11.93 11.93 0 01-5.232-4.963 11.98 11.98 0 01-1.463-6.886.975.975 0 011.943.173c-.178 2.005.246 4 1.226 5.769a9.968 9.968 0 003.526 3.685l4.586-9.405c-1.795-.598-3.29-.338-3.425-.312l-.058.012a.972.972 0 01-1.054-.576c-.24-.448-.96-1.544-1.834-1.97-.873-.426-2.218-.289-2.651-.195a.977.977 0 01-1.087-1.38C4.117.792 11.315-1.686 17.262 1.215c5.946 2.9 8.422 10.093 5.529 16.038l-.01.02c-2.903 5.94-10.095 8.414-16.039 5.514zm6.338-10.773l-4.586 9.405c4.629 1.73 9.896-.192 12.304-4.558-.338-.524-.932-1.275-1.62-1.61-.888-.434-2.19-.292-2.637-.198a.989.989 0 01-.616-.055.984.984 0 01-.49-.473c-.028-.058-.739-1.438-2.355-2.51zM5.81 6.56c.747.365 1.356.944 1.81 1.49 1.406-2.15 3.314-3.774 4.787-4.82a20.81 20.81 0 011.66-1.067A10.078 10.078 0 003.882 6.077c.617.042 1.297.174 1.929.482zm12.671-2.243c.09.624.152 1.294.182 1.965.083 1.801-.021 4.296-.844 6.722.686.018 1.484.14 2.214.495.652.318 1.198.8 1.628 1.28a10.082 10.082 0 00-3.18-10.462zm-5.394 5.46a9.522 9.522 0 012.984 2.287c1.075-3.493.606-7.402.215-8.85-1.381.584-4.75 2.62-6.84 5.618a9.515 9.515 0 013.64.944z" fill="#4137FF" />
        </G>
      </G>
      <Defs>
        <LinearGradient gradientUnits="userSpaceOnUse" id={id(1)} x1="6.75" x2="5.625" y1="20.55" y2="20.55">
          <Stop stopColor="#fff" />
          <Stop offset="1" stopOpacity="0" stopColor="#fff" />
        </LinearGradient>
        <LinearGradient gradientUnits="userSpaceOnUse" id={id(2)} x1="6.825" x2="7.2" y1="11.85" y2="11.137">
          <Stop stopOpacity="0" stopColor="#fff" />
          <Stop offset="1" stopColor="#fff" />
        </LinearGradient>
        <LinearGradient gradientUnits="userSpaceOnUse" id={id(3)} x1=".975" x2=".975" y1="20.512" y2="10.912">
          <Stop stopColor="#fff" />
          <Stop offset=".105" stopOpacity=".9" stopColor="#fff" />
          <Stop offset=".904" stopOpacity=".04" stopColor="#fff" />
          <Stop offset="1" stopOpacity="0" stopColor="#fff" />
        </LinearGradient>
        <ClipPath id={id(4)}>
          <Path d="M0 0h24v24H0z" fill="#fff" />
        </ClipPath>
      </Defs>
    </>
  ),
});
