// GENERATED by scripts/generate-icons.mjs from scripts/icon-manifest.json — do not edit.
import { G, Path } from 'react-native-svg';

import { createAiLogo } from '../create-ai-logo';

/** The xAI mark, drawn in one colour. */
export const AiLogoXAI = createAiLogo({
  name: "xAI",
  mono: ({ fill }) => (
    <G fill={fill} fillRule="evenodd">
      <Path d="M6.469 8.776L16.512 23h-4.464L2.005 8.776H6.47zm-.004 7.9l2.233 3.164L6.467 23H2l4.465-6.324zM22 2.582V23h-3.659V7.764L22 2.582zM22 1l-9.952 14.095-2.233-3.163L17.533 1H22z" />
    </G>
  ),
});
