// GENERATED by scripts/generate-icons.mjs from scripts/icon-manifest.json — do not edit.
import { G, Path } from 'react-native-svg';

import { createAiLogo } from '../create-ai-logo';

/** The Arcee AI mark — full colour by default, `variant="mono"` for one colour. */
export const AiLogoArcee = createAiLogo({
  name: "Arcee AI",
  mono: ({ fill }) => (
    <G fill={fill} fillRule="evenodd">
      <Path d="M13.236 2.377L2.751 20.493H0L11.863 0l1.373 2.377zm3.554 6.156l-9.606 11.96H4.13L15.511 6.32l1.279 2.212zm6.908 11.96H14.05l8.406-2.151 1.242 2.15zm-3.42-5.922l-7.843 5.92H8.482l10.597-7.997 1.2 2.077z" />
    </G>
  ),
  color: () => (
    <Path d="M13.236 2.377L2.751 20.493H0L11.863 0l1.373 2.377zm3.554 6.156l-9.606 11.96H4.13L15.511 6.32l1.279 2.212zm6.908 11.96H14.05l8.406-2.151 1.242 2.15zm-3.42-5.922l-7.843 5.92H8.482l10.597-7.997 1.2 2.077z" fill="#008C8C" />
  ),
});
