// GENERATED by scripts/generate-icons.mjs from scripts/icon-manifest.json — do not edit.
import { G, Path } from 'react-native-svg';

import { createAiLogo } from '../create-ai-logo';

/** The Tencent mark — full colour by default, `variant="mono"` for one colour. */
export const AiLogoTencent = createAiLogo({
  name: "Tencent",
  mono: ({ fill }) => (
    <G fill={fill} fillRule="evenodd">
      <Path d="M9.976 1L24 9.8l-10.587.015L10.723 23H5.489L8.18 9.8H3.244L1 5.4h8.077L9.976 1z" />
    </G>
  ),
  color: () => (
    <Path d="M9.976 1L24 9.8l-10.587.015L10.723 23H5.489L8.18 9.8H3.244L1 5.4h8.077L9.976 1z" fill="#0052D9" fillRule="evenodd" />
  ),
});
