// GENERATED by scripts/generate-icons.mjs from scripts/icon-manifest.json — do not edit.
import { G, Path } from 'react-native-svg';

import { createAiLogo } from '../create-ai-logo';

/** The Mistral AI mark — full colour by default, `variant="mono"` for one colour. */
export const AiLogoMistral = createAiLogo({
  name: "Mistral AI",
  mono: ({ fill }) => (
    <G fill={fill} fillRule="evenodd">
      <Path clipRule="evenodd" d="M3.428 3.4h3.429v3.428h3.429v3.429h-.002 3.431V6.828h3.427V3.4h3.43v13.714H24v3.429H13.714v-3.428h-3.428v-3.429h-3.43v3.428h3.43v3.429H0v-3.429h3.428V3.4zm10.286 13.715h3.428v-3.429h-3.427v3.429z" />
    </G>
  ),
  color: () => (
    <>
      <Path d="M3.428 3.4h3.429v3.428H3.428V3.4zm13.714 0h3.43v3.428h-3.43V3.4z" fill="gold" />
      <Path d="M3.428 6.828h6.857v3.429H3.429V6.828zm10.286 0h6.857v3.429h-6.857V6.828z" fill="#FFAF00" />
      <Path d="M3.428 10.258h17.144v3.428H3.428v-3.428z" fill="#FF8205" />
      <Path d="M3.428 13.686h3.429v3.428H3.428v-3.428zm6.858 0h3.429v3.428h-3.429v-3.428zm6.856 0h3.43v3.428h-3.43v-3.428z" fill="#FA500F" />
      <Path d="M0 17.114h10.286v3.429H0v-3.429zm13.714 0H24v3.429H13.714v-3.429z" fill="#E10500" />
    </>
  ),
});
