// GENERATED by scripts/generate-icons.mjs from scripts/icon-manifest.json — do not edit.
import { G, Path } from 'react-native-svg';

import { createAiLogo } from '../create-ai-logo';

/** The Inception mark, drawn in one colour. */
export const AiLogoInception = createAiLogo({
  name: "Inception",
  mono: ({ fill }) => (
    <G fill={fill} fillRule="evenodd">
      <Path d="M14.767 1H7.884L1 7.883v6.884h6.884V7.883h6.883V1zM9.234 23h6.882L23 16.116V9.233h-6.884v6.883H9.234V23z" />
    </G>
  ),
});
