// GENERATED by scripts/generate-icons.mjs from scripts/icon-manifest.json — do not edit.
import { G, Path } from 'react-native-svg';

import { createAiLogo } from '../create-ai-logo';

/** The Microsoft mark — full colour by default, `variant="mono"` for one colour. */
export const AiLogoMicrosoft = createAiLogo({
  name: "Microsoft",
  mono: ({ fill }) => (
    <G fill={fill} fillRule="evenodd">
      <Path d="M11.49 2H2v9.492h9.492V2h-.002z" />
      <Path d="M22 2h-9.492v9.492H22V2z" />
      <Path d="M11.49 12.508H2V22h9.492v-9.492h-.002z" />
      <Path d="M22 12.508h-9.492V22H22v-9.492z" />
    </G>
  ),
  color: () => (
    <>
      <Path d="M11.49 2H2v9.492h9.492V2h-.002z" fill="#F25022" />
      <Path d="M22 2h-9.492v9.492H22V2z" fill="#7FBA00" />
      <Path d="M11.49 12.508H2V22h9.492v-9.492h-.002z" fill="#00A4EF" />
      <Path d="M22 12.508h-9.492V22H22v-9.492z" fill="#FFB900" />
    </>
  ),
});
