// GENERATED by scripts/generate-icons.mjs from scripts/icon-manifest.json — do not edit.
import { G, Path } from 'react-native-svg';

import { createAiLogo } from '../create-ai-logo';

/** The Z.ai mark, drawn in one colour. */
export const AiLogoZAI = createAiLogo({
  name: "Z.ai",
  mono: ({ fill }) => (
    <G fill={fill} fillRule="evenodd">
      <Path d="M12.105 2L9.927 4.953H.653L2.83 2h9.276zM23.254 19.048L21.078 22h-9.242l2.174-2.952h9.244zM24 2L9.264 22H0L14.736 2H24z" />
    </G>
  ),
});
