// GENERATED by scripts/generate-icons.mjs from scripts/icon-manifest.json — do not edit.
import type { AiLogoComponent } from '../types';
import { AiLogoAi21 } from './AiLogoAi21';
import { AiLogoAionLabs } from './AiLogoAionLabs';
import { AiLogoAlibaba } from './AiLogoAlibaba';
import { AiLogoAlibabaCloud } from './AiLogoAlibabaCloud';
import { AiLogoAntGroup } from './AiLogoAntGroup';
import { AiLogoAnthropic } from './AiLogoAnthropic';
import { AiLogoArcee } from './AiLogoArcee';
import { AiLogoAws } from './AiLogoAws';
import { AiLogoBaidu } from './AiLogoBaidu';
import { AiLogoByteDance } from './AiLogoByteDance';
import { AiLogoClaude } from './AiLogoClaude';
import { AiLogoCohere } from './AiLogoCohere';
import { AiLogoDeepMind } from './AiLogoDeepMind';
import { AiLogoDeepSeek } from './AiLogoDeepSeek';
import { AiLogoDotsStudio } from './AiLogoDotsStudio';
import { AiLogoDoubao } from './AiLogoDoubao';
import { AiLogoGemini } from './AiLogoGemini';
import { AiLogoGoogle } from './AiLogoGoogle';
import { AiLogoGrok } from './AiLogoGrok';
import { AiLogoHuggingFace } from './AiLogoHuggingFace';
import { AiLogoHunyuan } from './AiLogoHunyuan';
import { AiLogoIbm } from './AiLogoIbm';
import { AiLogoInception } from './AiLogoInception';
import { AiLogoKimi } from './AiLogoKimi';
import { AiLogoKwaipilot } from './AiLogoKwaipilot';
import { AiLogoLiquid } from './AiLogoLiquid';
import { AiLogoLongCat } from './AiLogoLongCat';
import { AiLogoMeta } from './AiLogoMeta';
import { AiLogoMicrosoft } from './AiLogoMicrosoft';
import { AiLogoMiniMax } from './AiLogoMiniMax';
import { AiLogoMistral } from './AiLogoMistral';
import { AiLogoMoonshot } from './AiLogoMoonshot';
import { AiLogoNousResearch } from './AiLogoNousResearch';
import { AiLogoNova } from './AiLogoNova';
import { AiLogoNvidia } from './AiLogoNvidia';
import { AiLogoOpenAI } from './AiLogoOpenAI';
import { AiLogoPerplexity } from './AiLogoPerplexity';
import { AiLogoPoolside } from './AiLogoPoolside';
import { AiLogoQwen } from './AiLogoQwen';
import { AiLogoReka } from './AiLogoReka';
import { AiLogoRelace } from './AiLogoRelace';
import { AiLogoSakana } from './AiLogoSakana';
import { AiLogoStepFun } from './AiLogoStepFun';
import { AiLogoTencent } from './AiLogoTencent';
import { AiLogoTogether } from './AiLogoTogether';
import { AiLogoUpstage } from './AiLogoUpstage';
import { AiLogoWenxin } from './AiLogoWenxin';
import { AiLogoXAI } from './AiLogoXAI';
import { AiLogoXiaomi } from './AiLogoXiaomi';
import { AiLogoZAI } from './AiLogoZAI';
import { AiLogoZhipu } from './AiLogoZhipu';

/** Every mark, by registry key (lowercase, no separators). */
export const AI_PROVIDER_LOGOS = {
  ai21: AiLogoAi21,
  aionlabs: AiLogoAionLabs,
  alibaba: AiLogoAlibaba,
  alibabacloud: AiLogoAlibabaCloud,
  antgroup: AiLogoAntGroup,
  anthropic: AiLogoAnthropic,
  arcee: AiLogoArcee,
  aws: AiLogoAws,
  baidu: AiLogoBaidu,
  bytedance: AiLogoByteDance,
  claude: AiLogoClaude,
  cohere: AiLogoCohere,
  deepmind: AiLogoDeepMind,
  deepseek: AiLogoDeepSeek,
  dotsstudio: AiLogoDotsStudio,
  doubao: AiLogoDoubao,
  gemini: AiLogoGemini,
  google: AiLogoGoogle,
  grok: AiLogoGrok,
  huggingface: AiLogoHuggingFace,
  hunyuan: AiLogoHunyuan,
  ibm: AiLogoIbm,
  inception: AiLogoInception,
  kimi: AiLogoKimi,
  kwaipilot: AiLogoKwaipilot,
  liquid: AiLogoLiquid,
  longcat: AiLogoLongCat,
  meta: AiLogoMeta,
  microsoft: AiLogoMicrosoft,
  minimax: AiLogoMiniMax,
  mistral: AiLogoMistral,
  moonshot: AiLogoMoonshot,
  nousresearch: AiLogoNousResearch,
  nova: AiLogoNova,
  nvidia: AiLogoNvidia,
  openai: AiLogoOpenAI,
  perplexity: AiLogoPerplexity,
  poolside: AiLogoPoolside,
  qwen: AiLogoQwen,
  reka: AiLogoReka,
  relace: AiLogoRelace,
  sakana: AiLogoSakana,
  stepfun: AiLogoStepFun,
  tencent: AiLogoTencent,
  together: AiLogoTogether,
  upstage: AiLogoUpstage,
  wenxin: AiLogoWenxin,
  xai: AiLogoXAI,
  xiaomi: AiLogoXiaomi,
  zai: AiLogoZAI,
  zhipu: AiLogoZhipu,
} as const satisfies Record<string, AiLogoComponent>;

export type AiProviderLogoKey = keyof typeof AI_PROVIDER_LOGOS;
